# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161115_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='course_id',
            new_name='course',
        ),
    ]
